/** @format */

import React from "react";
import { Story, Meta } from "@storybook/react";

import HomescreenMainapp from "./HomescreenMainapp";

import { HomescreenMainappProps } from "./HomescreenMainapp.types";

export default {
  title: "Pages/HomescreenMainapp",
  component: HomescreenMainapp,
  argTypes: {},
} as Meta<typeof HomescreenMainapp>;

const Template: Story<HomescreenMainappProps> = (args) => (
  <HomescreenMainapp {...args} />
);

export const Default = Template.bind({});
Default.args = {
  selectedTopics: ["Versorgung"],
  ideaData: [
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
    {
      Stadtteil: "Mülheim",
      Thema: "Sport / Freizeit",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      color: "#f6c095",
      commentCount: 0,
      createdAt: "2021-07-12T11:10:22.413Z",
      lat: 50.96734458192481,
      likeCount: 1,
      locationHeader: "Mülheimer Freiheit 142",
      long: 7.00181320821256,
      screamId: "omweqsDYlFMkmTFAX1Ba",
      status: "None",
      title: "Straßenfest an der Wallstraße",
    },
  ],
  organizationsData: [
    {
      address: null,
      contact: "",
      createdAt: "2022-03-23T15:36:09.859Z",
      description: "asdlkasdasd askjhdhaskjdhaskkd",
      faqs: null,
      imgUrl:
        "https://firebasestorage.googleapis.com/v0/b/senf-dev.appspot.com/o/organizationsData%2FQO0SOuQBIc9wEjpayU9e%2Flogo%2Flogo?alt=media&token=131ee6fa-19a0-4ee9-b8c0-43909e2373d6",
      latitude: null,
      longitude: null,
      organizationId: "HNgqF5rjKfdjb7GxaPuK",
      organizationType: "Vereine",
      status: "active",
      title: "Tazy's organisation",
      userIds: ["EkLheyhRjYSCMyUd4qvMIng0as43"],
      weblink: "",
    },
    {
      address: null,
      contact: "",
      createdAt: "2022-03-23T15:36:09.859Z",
      description: "asdlkasdasd askjhdhaskjdhaskkd",
      faqs: null,
      imgUrl:
        "https://firebasestorage.googleapis.com/v0/b/senf-dev.appspot.com/o/organizationsData%2FQO0SOuQBIc9wEjpayU9e%2Flogo%2Flogo?alt=media&token=131ee6fa-19a0-4ee9-b8c0-43909e2373d6",
      latitude: null,
      longitude: null,
      organizationId: "HNgqF5rjKfdjb7GxaPuK",
      organizationType: "Vereine",
      status: "active",
      title: "Tazy's organisation",
      userIds: ["EkLheyhRjYSCMyUd4qvMIng0as43"],
      weblink: "",
    },
    {
      address: null,
      contact: "",
      createdAt: "2022-03-23T15:36:09.859Z",
      description: "asdlkasdasd askjhdhaskjdhaskkd",
      faqs: null,
      imgUrl:
        "https://firebasestorage.googleapis.com/v0/b/senf-dev.appspot.com/o/organizationsData%2FQO0SOuQBIc9wEjpayU9e%2Flogo%2Flogo?alt=media&token=131ee6fa-19a0-4ee9-b8c0-43909e2373d6",
      latitude: null,
      longitude: null,
      organizationId: "HNgqF5rjKfdjb7GxaPuK",
      organizationType: "Vereine",
      status: "active",
      title: "Tazy's organisation",
      userIds: ["EkLheyhRjYSCMyUd4qvMIng0as43"],
      weblink: "",
    },
  ],
};
