/** @format */

import React from "react";
import { Story, Meta } from "@storybook/react";

import ProjectroomPage from "./ProjectroomPage";

import { ProjectroomPageProps } from "./ProjectroomPage.types";

export default {
  title: "Pages/ProjectroomPage",
  component: ProjectroomPage,
  argTypes: {},
} as Meta<typeof ProjectroomPage>;

const ProjectroomPageTemplate: Story<ProjectroomPageProps> = (args) => (
  <ProjectroomPage {...args} />
);

export const Projectroom = ProjectroomPageTemplate.bind({});
Projectroom.args = {
  data: {
    logoURL:
      "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/organizationsData%2FXaZl7rCTh5PVQKE4hQvj%2FRHeBEXczxNIE5RsF4JG9%2Fthumbnail?alt=media&token=889689e4-7fad-484c-a343-7ddf45b5cc39",
    weblinkTitle: "Offener Brief",
    createdAt: "2022-02-14T14:43:00.958Z",
    organizationId: "XaZl7rCTh5PVQKE4hQvj",
    zoom: 17,
    centerLong: 6.941211826858762,
    owner: "United Eifelwall",
    projectRoomId: "RHeBEXczxNIE5RsF4JG9",
    geoData:
      '{"type":"FeatureCollection","features":[{"id":"9a44a6b844f74745a296eefe4dced979","type":"Feature","properties":{},"geometry":{"coordinates":[[[6.940460066328626,50.92316119587858],[6.94034160709279,50.92296589892973],[6.941954475141102,50.92195493691344],[6.9420820466247335,50.92204684345916],[6.940460066328626,50.92316119587858]]],"type":"Polygon"}}]}',
    description_about:
      "unseren Eifelwall! Seit ein Teil des Eifelwalls autofrei ist, entfaltete sich dort das Leben. Er wurde immer lebendiger und von vielen unterschiedlichen Menschen und Gruppen genutzt und wurde so zu einem Begegnungs- und Aktivort, der frei, selbstverwaltet und unkommerziell war.",
    contact: null,
    status: "active",
    contactTitle: null,
    description_procedure:
      "den Ort zu einem spannenden Reallabor aufblühen lassen, der zeigt, wie sich eine Stadt mit Wünschen der Bürger:innen entwickeln lässt. ",
    weblink:
      "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/2021-10-31_O%CC%88ffentlicher%20Raum%20Eifelwall.pdf?alt=media&token=0f54a43b-7b39-4353-88c6-7ee6c171f15c",
    brief:
      "Teilt eure Ideen für den neu entstandenen Raum am Eifelwall und helft dabei, einen lebenswerten Ort entstehen zu lassen.",
    organizationType: "Initiativen",
    description_motivation:
      "es zu zeigen, wie ein öffentlicher Ort von Menschen für Menschen geschaffen und frei gestaltet werden kann, auch wenn die Stadt uns ein paar Steine in den Weg legt. ",
    description_learnmore:
      "schau doch mal in unseren offenen Brief an die Stadt Köln rein! Dort findest du Eindrücke von unseren bisherigen Vorstellungen und auch den frustrierenden Räumungsaktionen des Ordnungsamtes. ",
    title: "Neugestaltung des Eifelwalls  ",
    centerLat: 50.92255806639601,
    screams: [
      {
        sex: "female",
        commentCount: 0,
        likeCount: 5,
        projectRoomId: "RHeBEXczxNIE5RsF4JG9",
        userId: "5YCo7aemL8NaXjEeRfLmICSprMr2",
        createdAt: "2021-11-15T22:58:29.005Z",
        long: 6.941094135901949,
        status: "None",
        body: "Ich fände es eine coole Idee, wenn der Eifelwall eine Anlaufstelle für Pflanzenableger werden würde. Jede:r der mag kann",
        project: "UnitedEifelwall:_Neugestaltung_des_Eifelwalls",
        locationHeader: "Eifelwall 1",
        userHandle: "Ming Hätz schläät för Kölle",
        age: 28,
        Thema: "Umwelt und Grün",
        lat: 50.92250431204894,
        title: "Pflanzen-Tauschbörse/ urban gardening",
        Stadtteil: "Neustadt",
        district: "Eifelwall 1, 50674 Köln, Germany",
        screamId: "JRPmVPNI8GsO6IiArOr4",
        color: "#8dd9b8",
      },
      {
        commentCount: 0,
        long: 6.941147240910084,
        Thema: "Versorgung",
        likeCount: 5,
        userHandle: "Marie",
        status: "None",
        locationHeader: "Eifelwall 1",
        sex: "",
        lat: 50.92257604599973,
        projectRoomId: "RHeBEXczxNIE5RsF4JG9",
        body: "Es wäre cool, wenn für gerettete Lebensmittel, zum Beispiel Backwaren, ein Aufbewahrungsort (Fairteiler) eingerichtet we",
        Stadtteil: "Neustadt",
        title: "Fairteiler für gerettete Lebensmittel 🥐🥑",
        createdAt: "2021-11-15T22:46:04.215Z",
        age: "",
        district: "Eifelwall 1, 50674 Köln, Germany",
        project: "UnitedEifelwall:_Neugestaltung_des_Eifelwalls",
        userId: "kcKVK0XBQWab39Wc90YFK8XAZfo1",
        screamId: "a1kIIYNQOyndR0QRtUqj",
        color: "#bd98f6",
      },
      {
        userHandle: "deintillmann ",
        Stadtbezirk: "Innenstadt",
        commentCount: 0,
        selectedUnix: null,
        createdAt: "2021-11-02T10:47:23.910Z",
        userId: "1145vMjgGRQpDLkLPJCIOrgreBv1",
        district: "Eifelwall 1, 50674 Köln, Germany",
        contact: null,
        Stadtteil: "Neustadt/Süd",
        subjectivity: 0,
        screamId: "KOpWe7EolPU1THxnEnm4",
        contactTitle: null,
        polarity: 0,
        projectRoomId: "RHeBEXczxNIE5RsF4JG9",
        lat: 50.92249716269775,
        age: "",
        project: "UnitedEifelwall:_Neugestaltung_des_Eifelwalls",
        sex: "",
        color: "#929df6",
        Thema: "Rad",
        title: "Farbiger Fahrrad weg",
        weblink: null,
        body: "Um den Platz etwas bunter, freundlicher und sicher zu machen, wäre eine Bodenmarkierung für Fahrräder nett.  ",
        likeCount: 11,
        status: "None",
        long: 6.941323192195516,
        weblinkTitle: null,
        locationHeader: "Eifelwall 1",
      },
      {
        title: "Fahrradreparaturstation",
        screamId: "dQFfwfZzn3UtCdcaLdro",
        Stadtbezirk: "Innenstadt",
        subjectivity: 0,
        createdAt: "2021-11-01T21:14:42.924Z",
        body: "Eine öffentliche fahrradreparaturstation mit Werkzeugen und einer Pumpe wäre eine gute Ergänzung für den Eifelwall.\nWer ",
        project: "UnitedEifelwall:_Neugestaltung_des_Eifelwalls",
        Thema: "Rad",
        contactTitle: null,
        commentCount: 0,
        userId: "0huufA2BVpSAMh0gZeZInXAbd322",
        lat: 50.92262865082154,
        color: "#929df6",
        district: "Eifelwall 1, 50674 Köln, Germany",
        projectRoomId: "RHeBEXczxNIE5RsF4JG9",
        likeCount: 11,
        sex: "male",
        polarity: 0,
        weblinkTitle: "Beispiele ",
        contact: null,
        status: "None",
        long: 6.941177586668958,
        Stadtteil: "Neustadt/Süd",
        weblink: "https://www.radstelle.eu/fahrradreparaturstationen/",
        locationHeader: "Eifelwall 1",
        selectedUnix: null,
        age: 25,
        userHandle: "Momo",
      },
      {
        sex: "female",
        long: 6.941147240910084,
        weblink: null,
        district: "Eifelwall 1, 50674 Köln, Germany",
        status: "None",
        subjectivity: 0,
        selectedUnix: null,
        userId: "6TlwZM81o3WiCDU7zMhHdHbLMZh2",
        weblinkTitle: null,
        contact: null,
        age: 49,
        likeCount: 11,
        Stadtteil: "Neustadt/Süd",
        lat: 50.92257604599973,
        userHandle: "Südstadion ",
        commentCount: 0,
        body: "In Kombi mit der Idee „bunte Lichter“ und „Bücherschrank“ wäre ein Verweilmöglichkeit (ggfs auf Rädern wg Mobilität schö",
        contactTitle: null,
        color: "#f6c095",
        projectRoomId: "RHeBEXczxNIE5RsF4JG9",
        Thema: "Sport / Freizeit",
        project: "UnitedEifelwall:_Neugestaltung_des_Eifelwalls",
        locationHeader: "Eifelwall 1",
        title: "Sitzgelegenheiten & Begrünung",
        screamId: "pHN8gGnJ85r6WPpmTKdt",
        polarity: 0,
        Stadtbezirk: "Innenstadt",
        createdAt: "2021-11-01T08:28:56.517Z",
      },
      {
        Stadtbezirk: "Innenstadt",
        userId: "GeCIJBcV4fh4jl06elRGfoi3uxx2",
        Thema: "Sonstige",
        Stadtteil: "Neustadt/Süd",
        project: "UnitedEifelwall:_Neugestaltung_des_Eifelwalls",
        projectRoomId: "RHeBEXczxNIE5RsF4JG9",
        color: "#f9db95",
        createdAt: "2021-10-30T09:28:41.998Z",
        title: "Bunte Lichter/Lampen",
        age: 28,
        locationHeader: "Eifelwall 1",
        commentCount: 1,
        lat: 50.9224222164085,
        likeCount: 12,
        body: "Würds super finden kreative Beleuchtung vor Ort zu installieren. Mit der Kulisse mit den Brücken kann das Hammer aussehe",
        long: 6.941494952421761,
        subjectivity: 0,
        sex: "male",
        status: "None",
        userHandle: "FloUndzig",
        polarity: 0,
        district: "Eifelwall 1, 50674 Köln, Germany",
        screamId: "dHC57BHXYQVX1Ksv4qhp",
      },
      {
        likeCount: 11,
        long: 6.940714814266908,
        age: 28,
        commentCount: 0,
        Stadtbezirk: "Innenstadt",
        title: "Öffentlicher Bücherkasten",
        subjectivity: 0,
        projectRoomId: "RHeBEXczxNIE5RsF4JG9",
        lat: 50.92291080294504,
        body: "Ich würde mir für den Ort ein öffentliches Bücherregal wünschen, so dass man dort wie bei sich zu Hause schmökern und vo",
        color: "#bd98f6",
        district: "Eifelwall 1, 50674 Köln, Germany",
        sex: "male",
        status: "None",
        createdAt: "2021-10-29T06:23:09.802Z",
        userId: "xVndCi8g0iedePUy6pVO2JDfRG32",
        userHandle: "PeCe",
        locationHeader: "Eifelwall 1",
        project: "UnitedEifelwall:_Neugestaltung_des_Eifelwalls",
        Thema: "Versorgung",
        polarity: 0,
        Stadtteil: "Neustadt/Süd",
        screamId: "GmyVMlEr1Ll9OpwlGjmC",
      },
      {
        title: "Treffpunkt",
        Stadtbezirk: "Innenstadt",
        createdAt: "2021-10-07T18:48:20.922Z",
        screamId: "sg8nLvzQtrQNTCIHQSGi",
        userId: "38T1R8XrdbTMxjGZJZMwmb1aob72",
        district: "Eifelstraße 66, 50677 Köln, Germany",
        likeCount: 9,
        project: "UnitedEifelwall:_Neugestaltung_des_Eifelwalls",
        commentCount: 1,
        Thema: "Sport / Freizeit",
        status: "None",
        contact: null,
        projectRoomId: "RHeBEXczxNIE5RsF4JG9",
        age: 25,
        contactTitle: null,
        selectedUnix: null,
        polarity: 0,
        long: 6.9417123525184845,
        weblink: null,
        locationHeader: "Eifelstraße 66",
        weblinkTitle: null,
        sex: "male",
        subjectivity: 0,
        body: "Auf der stillgelegten Straßenverbindung zwischen Höninger Weg und Eifelwall hat sich im letzten Jahr peu a peu ein Wunde",
        Stadtteil: "Neustadt/Süd",
        color: "#f6c095",
        userHandle: "JakobiusHolz",
        lat: 50.92300936634372,
      },
    ],
  },
  organizations: [
    {
      address: null,
      faqs: null,
      title: "United Eifelwall",
      description:
        "Seitdem der Eifelwall zwischen der Eifelstraße und der Rudolf-Amelunxen-Straße autofrei ist, wird er immer lebendiger und von vielen unterschiedlichen Menschen und Gruppen täglich in ihrer Freizeit erfahren und gemeinschaftlich – aber trotzdem unabhängig voneinander – genutzt. Es ist ein Begegnungs- und Aktivort, der frei, selbstverwaltet und unkommerziell ist.  ",
      logoURL:
        "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/2021-10-31_O%CC%88ffentlicher%20Raum%20Eifelwall.pdf?alt=media&token=0f54a43b-7b39-4353-88c6-7ee6c171f15c",
      weblink: null,
      contactTitle: null,
      contact: null,
      organizationType: "Initiativen",
      status: "active",
      organizationId: "XaZl7rCTh5PVQKE4hQvj",
      longitude: null,
      latitude: null,
      createdAt: "2022-02-14T14:05:20.049Z",
      weblinkTitle: null,
      userIds: ["qkbwKh9DT3h4h6yPsH8D7GqYRXC3"],
    },
  ],
};
