/** @format */

import React from "react";
import { Story, Meta } from "@storybook/react";

import MainSwipeList from "./MainSwipeList";

import { MainSwipeListProps } from "./MainSwipeList.types";

export default {
  title: "Pages/MainSwipeList",
  component: MainSwipeList,
  argTypes: {},
} as Meta<typeof MainSwipeList>;

const Template: Story<MainSwipeListProps> = (args) => (
  <MainSwipeList {...args} />
);
export const Default = Template.bind({});
Default.args = {
  order: "ideas",
  selectedTopics: ["Versorgung"],
  checkedSortOption: "newest",
  ideasData: [
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
  ],
};

export const SwipedUp = Template.bind({});
SwipedUp.args = {
  swipedUp: true,
  order: "ideas",
  selectedTopics: ["Versorgung"],

  ideasData: [
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
  ],
};

export const ProjectRoomSwipeList = Template.bind({});
ProjectRoomSwipeList.args = {
  order: "projectrooms",

  selectedTopics: ["Versorgung"],
  selectedOrganizationTypes: ["Vereine"],

  projectroomsData: [
    {
      centerLat: 50.96447910444719,
      zoom: 12.5,
      description_about: "room description",
      description_procedure: "room description",
      organizationType: "Initiativen",
      projectRoomId: "Y2dFTmJ2FIzD1YqPCotk",
      weblinkTitle: "Website",
      description_learnmore: null,
      contactTitle: "Kontakt",
      owner: "Neue Organisation",
      createdAt: "2022-05-31T12:41:10.338Z",
      weblink: "",
      geoData:
        '{"type":"FeatureCollection","features":[{"id":"1fd84b9011288075e06623625fed2972","type":"Feature","properties":{},"geometry":{"coordinates":[[[6.848024518461614,50.99077694309838],[6.95969680827622,50.938181265796004],[6.9300793748909655,50.969378911207144],[6.848024518461614,50.99077694309838]]],"type":"Polygon"}}]}',
      status: "active",
      calendar: false,
      title: "room description",
      contact: "",
      logoURL:
        "https://firebasestorage.googleapis.com/v0/b/senf-dev.appspot.com/o/organizationsData%2FrATYNDh5gfJGYMTKlCVC%2FY2dFTmJ2FIzD1YqPCotk%2Fthumbnail?alt=media&token=b805c2fe-e647-453e-a057-9cca7108b8a4",
      centerLong: 6.903860663368917,
      description_motivation: null,
      organizationId: "rATYNDh5gfJGYMTKlCVC",
      brief: "room description",
      icon: {
        type: "svg",
        key: null,
        ref: null,
        props: {
          id: "Ebene_1",
          "data-name": "Ebene 1",
          xmlns: "http://www.w3.org/2000/svg",
          viewBox: "0 0 16 16",
          children: [
            {
              type: "path",
              key: null,
              ref: null,
              props: {
                d: "M7.35,12.66a1.08,1.08,0,0,1-.46.27.18.18,0,0,0-.13.15L6.6,14.47a.72.72,0,0,0,.64.81.73.73,0,0,0,.61-.21l1.9-1.9a5.51,5.51,0,0,0,1.16-1.75,8.59,8.59,0,0,0,.26-2.14A.17.17,0,0,0,11,9.09a.19.19,0,0,0-.13.05Z",
              },
              _owner: null,
            },
            {
              type: "path",
              key: null,
              ref: null,
              props: {
                d: "M3.35,8.66,6.88,5.11a.18.18,0,0,0,0-.25.19.19,0,0,0-.13-.05,9.06,9.06,0,0,0-2.2.25A5.5,5.5,0,0,0,2.83,6.24L.93,8.14a.73.73,0,0,0,0,1,.72.72,0,0,0,.52.21l1.49-.17a.18.18,0,0,0,.15-.13A1.06,1.06,0,0,1,3.35,8.66Z",
              },
              _owner: null,
            },
            {
              type: "path",
              key: null,
              ref: null,
              props: {
                d: "M3.75,11.24a1.54,1.54,0,0,0-2.27.25A10.76,10.76,0,0,0,0,15.1.73.73,0,0,0,.53,16,.77.77,0,0,0,.9,16a10.91,10.91,0,0,0,3.6-1.46,1.54,1.54,0,0,0,.25-2.27Z",
              },
              _owner: null,
            },
            {
              type: "path",
              key: null,
              ref: null,
              props: {
                d: "M15.58,0a8.65,8.65,0,0,0-3.24,1.15c-.46.46-7.1,7.13-8.11,8.12a.19.19,0,0,0,0,.26l2.24,2.24a.2.2,0,0,0,.25,0l8.12-8.12A8.48,8.48,0,0,0,16,.42.35.35,0,0,0,15.71,0Z",
              },
              _owner: null,
            },
          ],
        },
        _owner: null,
      },
    },
  ],

  organizations: [
    {
      weblinkTitle: "Website",
      description:
        "Wir tragen zur sozial-ökologischen Transformation der Stadt Köln bei und arbeiten an Lösungen in den Bereichen Mobilität, Klimaschutz, Stadtgestaltung, soziale Gerechtigkeit und Kultur. Durch lokale Projekte sollen die nachbarschaftlichen Strukturen und somit die Stadtentwicklung von unten gefördert werden! Im Fokus steht eine zukunftsfähige, nachhaltige und lebenswerte Stadt.",
      organizationId: "7neEcENX16eIw4baKwXC",
      title: "Agora Koeln e.V.",
      longitude: 6.9236645,
      contactTitle: "E-Mail",
      weblink: "https://www.agorakoeln.de/",
      logoURL:
        "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/organizationsData%2F7neEcENX16eIw4baKwXC%2Flogo%2Flogo?alt=media&token=0738d077-b146-4519-bcc3-017538e09f8e",
      address: "Körnerstraße 77, 50823 Köln, Germany",
      organizationType: "Vereine",
      createdAt: "2022-02-14T13:43:51.856Z",
      userIds: ["qkbwKh9DT3h4h6yPsH8D7GqYRXC3", "TUjbkR6OATOPvIa12CikQFDIiVR2"],
      contact: "info@agorakoeln.de",
      status: "active",
      latitude: 50.9502088,
      faqs: [
        {
          answer:
            "Schau mal bei unseren aktuellen Projekten (LINK) nach und melde dich bei den jeweiligen Projekt-Ansprechpartner:innen oder schreib uns eine Mail - wir helfen dir gern dabei etwas passendes zu finden und freuen uns über deine Mitarbeit.",
          question: "Wie kann ich mitmachen?",
        },
        {
          answer:
            "Jede:r, dier/der im Veedel etwas bewegen möchte - wir haben viele verschiedene Projekte, von denen bestimmt etwas dabei ist.",
          question: "Wer kann mitmachen?",
        },
      ],
    },
    {
      faqs: null,
      userIds: ["qkbwKh9DT3h4h6yPsH8D7GqYRXC3"],
      longitude: null,
      latitude: null,
      status: "active",
      logoURL:
        "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/2021-10-31_O%CC%88ffentlicher%20Raum%20Eifelwall.pdf?alt=media&token=0f54a43b-7b39-4353-88c6-7ee6c171f15c",
      weblinkTitle: null,
      organizationType: "Initiativen",
      address: null,
      organizationId: "XaZl7rCTh5PVQKE4hQvj",
      description:
        "Seitdem der Eifelwall zwischen der Eifelstraße und der Rudolf-Amelunxen-Straße autofrei ist, wird er immer lebendiger und von vielen unterschiedlichen Menschen und Gruppen täglich in ihrer Freizeit erfahren und gemeinschaftlich – aber trotzdem unabhängig voneinander – genutzt. Es ist ein Begegnungs- und Aktivort, der frei, selbstverwaltet und unkommerziell ist.  ",
      contactTitle: null,
      weblink: null,
      title: "United Eifelwall",
      createdAt: "2022-02-14T14:05:20.049Z",
      contact: null,
    },
    {
      contact: "kontakt@wandelwerk.koeln",
      userIds: ["qkbwKh9DT3h4h6yPsH8D7GqYRXC3"],
      address: "Liebigstraße 201, 50823 Köln, Germany",
      createdAt: "2022-02-14T14:02:15.465Z",
      organizationType: "Initiativen",
      title: "WandelWerk",
      status: "active",
      contactTitle: "E-Mail",
      longitude: 6.9347702,
      description:
        "Das WandelWerk steht für den sozial-ökologischen Wandel in Köln. Wir sind davon überzeugt, dass es einen Ort braucht, für all jene, die sich für die klimafreundliche und faire Stadt von morgen einsetzen. Hier können sich engagierte Kölner:innen vernetzen und Hand in Hand an der Vision für ein gutes Leben für alle arbeiten. \n\nWir bringen Menschen mit all ihren unterschiedlichen Ideen und Fähigkeiten zusammen und setzen Ideen für eine bessere Welt gemeinsam um.\n\nWir arbeiten mit dem Verständnis von Wertschöpfung, das über das finanzielle hinausgeht und Wirtschaft vor allem im Sinne des Gemeinwohls denkt.",
      weblink: "https://wandelwerk.koeln/",
      latitude: 50.9567265,
      faqs: null,
      organizationId: "dlLtQlMS2xmyA5R2oQkb",
      logoURL:
        "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/organizationsData%2FdlLtQlMS2xmyA5R2oQkb%2Flogo%2Flogo?alt=media&token=2fad30c9-d391-4d49-85b2-fc6bc98b6070",
      weblinkTitle: "Website",
    },
    {
      googleCalendarId: "rpanecgkom2lsu6jid6db0a6qk@group.calendar.google.com",
      latitude: null,
      faqs: [
        {
          answer:
            "„Einmischen“ kann auch heißen: mitmachen | teilnehmen | sich beteiligen | sich einschalten | eingreifen | beanstanden | protestieren | kritisieren | vermitteln | ein Wort einlegen für … | Einspruch erheben | intervenieren | mitmischen | mitsprechen | ein Wörtchen mitzureden haben | seine Meinung äußern | neugierig sein | wissen wollen, …\nAlso: Wir verbinden hiermit verschiedensten Formen des im weiteren Sinne politischen bzw. bürgerschaftlichen Engagements für eine gute Sache, gegen schlechte Sachen, für gesellschaftliche Neuerungen u.a.m.\nDas „Einmischen“ ermöglichen ist wesentliches Anliegen des Bereiches „Politische Partizipation“ der Kölner Freiwilligen Agentur (https://www.koeln-freiwillig.de/beteiligen/).",
          question: "Was meint „Einmischen“?",
        },
        {
          question:
            "Was bedeutet „Systematische Öffentlichkeitsbeteiligung“ in Köln?",
          answer:
            "In einem umfassenden Prozess wurden Leitlinien für die „Systematische Öffentlichkeitsbeteiligung“ von Vertreterinnen und Vertretern aus Politik, Verwaltung und nicht zuletzt der Kölner Stadtgesellschaft erarbeitet. Auf dieser Grundlage sind aktuell die Stadtbezirke Kalk, Lindenthal und Nippes sowie die Ratsausschüsse „Klima, Umwelt und Grün“ und „Verkehrsausschuss“ bei allen städtischen Vorhaben, über die sie entscheiden, zugleich auch über die Öffentlichkeitsbeteiligung zu beschließen. Eine Übersicht über die aktuell beschlossenen und stattfindenden Beteiligungsverfahren sind auf dem Beteiligungsportal https://www.meinungfuer.koeln/ zu finden. Hier gibt es auch umfassende Infos zu den Leitlinien.\n\nUnter https://www.koeln-freiwillig.de/mitmachen/oeb/ gibt es jeweils eine aktuelle Übersicht über zur Entscheidung anstehende Vorlagen, bei denen eine Öffentlichkeitsbeteiligung vorgesehen ist oder abgelehnt wird.",
        },
        {
          answer:
            "Wenn du eine für dich, dein Zeitbudget und deine Interessen passende Engagementmöglichkeit suchst, kannst dich hier auf der KFA-Website informieren: https://www.koeln-freiwillig.de/engagementberatung/. Oder du vereinbarst einen persönlichen Beratungstermin.\nWenn du dich für die Verwirklich deiner hier bei senf.koeln eingebrachte Idee engagieren und dazu z.B. eine Initiative gründen willst beraten wir (KFA-Bereich „Politische Partizipation“) dich gerne. Schick uns eine E-Mail (beteiligen@koeln-freiwillig.de) oder nutze unsere in der Regel wöchentlich angebotene offene Online-Sprechstunde: https://www.koeln-freiwillig.de/sprechstunde",
          question: "Wo bzw. wie kann ich mich engagieren?",
        },
        {
          question: "Wie kann ich ein Anliegen auf den Weg bringen?",
          answer:
            "Wenn du eine kleineres oder größeres Anliegen hast, das ein Handeln oder eine Entscheidung vonseiten der Verwaltung oder der Rats- bzw. Bezirkspolitik erfordert, gibt es mehre Möglichkeiten und auch Eskalationsstufen: vom Anruf über eine Petitionen („Anregung“ oder „Beschwerde“) bis hin zum Bürgerentscheid. Eine Übersicht über die rechtlich möglichen und von der Stadt Köln gebotenen Möglichkeiten findest du hier: https://www.stadt-koeln.de/politik-und-verwaltung/mitwirkung/\nWenn du da nicht weiter kommst oder das nicht passt, können wir (KFA-Bereich „Politische Partizipation“) dich gerne beraten. Schick uns eine E-Mail (beteiligen@koeln-freiwillig.de) oder nutze unsere in der Regel wöchentlich angebotene offene Online-Sprechstunde: https://www.koeln-freiwillig.de/sprechstunde",
        },
        {
          question:
            "Welche Beratungs- oder Unterstützungsmöglichkeiten gibt es für meine senf-Idee oder Initiative?",
          answer:
            "Wir, der Bereich „Politische Partizipation“ der Kölner Freiwilligen Agentur, bieten folgende Möglichkeiten der Beratung, Qualifizierung oder auch weiter gehenden Unterstützung an:\n\n- In der Regel 1x wöchentlich eine offene Online-Sprechstunde. https://www.koeln-freiwillig.de/sprechstunde\n\n- Vertiefende Einzelberatungen insbesondere für Initiativen in Gründung. (Terminvereinbarung per E-Mail beteiligen@koeln-freiwillig.de bzw. telefonisch 0221 888 278-16)\n\n- Moderation bei Gründungsversammlungen z.B.\nVertiefende Qualifizierungen zu verschiedenen Aspekten der Initiativearbeit wie: Öffentlichkeitsarbeit, Gewinnung Engagierter, Fundraising / Spendengewinnung, \n\n- Vereinsentwicklung, Aktionen & Kampagnen u.a.m. Eine jeweils aktuelle Übersicht der Angebote ist hier zu finden: https://www.koeln-freiwillig.de/beteiligen/quali-fuer-inis/",
        },
      ],
      userIds: [
        "qkbwKh9DT3h4h6yPsH8D7GqYRXC3",
        "sSjkXTPMxmTxHxpmShEyCSTiQh22",
        "UZV51kRqaJTlDeb6iyfjveIgoq53",
      ],
      status: "active",
      createdAt: "2022-03-07T20:11:51.519Z",
      organizationType: "Vereine",
      contact: "beteiligen@koeln-freiwillig.de",
      weblinkTitle: "Website",
      weblink: "https://www.koeln-freiwillig.de/beteiligen",
      longitude: null,
      logoURL:
        "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/organizationsData%2Fh3UPecBj7QoHNA6SkYe3%2Flogo%2Flogo?alt=media&token=a7db2686-f816-4d5f-b491-dcac08493925",
      title: "Kölner Freiwilligen Agentur e.V.",
      description:
        "Wir wollen erreichen, dass alle Menschen das öffentliche Leben in Köln und eine gute Entwicklung der Stadt mitgestalten und bereichern (können). Hierzu beraten und unterstützen wir Interessierte bei der Suche nach geeigneten Engagementmöglichkeiten oder auch bei der Gründung eigener Initiativen. Unter dem Leitmotiv „Einmischen ist erwünscht und möglich!“ informieren wir über Möglichkeiten der Bürgerbeteiligung, der politischen Teilhabe und wie es gelingen kann, ein Anliegen z.B. für den öffentlichen Raum bzw. das öffentliche Leben Erfolg versprechend auf den Weg zu bringen.",
      organizationId: "h3UPecBj7QoHNA6SkYe3",
      contactTitle: "E-Mail",
      address: "Clemensstraße 7, 50676 Köln, Germany",
    },
    {
      latitude: 50.951076,
      longitude: 6.9585977,
      userIds: ["qkbwKh9DT3h4h6yPsH8D7GqYRXC3", "TUjbkR6OATOPvIa12CikQFDIiVR2"],
      organizationId: "sn6M3uThZFrR40OV3aiT",
      logoURL:
        "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/organizationsData%2Fsn6M3uThZFrR40OV3aiT%2Flogo%2Flogo?alt=media&token=3ae074ac-cdc8-426f-a8d6-3c772674e690",
      weblinkTitle: "Website",
      status: "active",
      organizationType: "Politik",
      createdAt: "2022-02-14T14:03:39.878Z",
      contactTitle: "E-Mail",
      description:
        "Ganz nah an den Orten und Themen der Stadt, ganz nah bei den Bürgerinnen und Bürgern sein - Politik vor Ort ist eine spannende Angelegenheit! \n\nWir möchten unsere grüne Politik raus aus den Gremien und Arbeitskreisen tragen. Und was liegt da näher, als sich in der Kneipe mit dem Bürger/der Bürgerin zu verabreden. ",
      contact: "innenstadt@gruenekoeln.de",
      weblink: "https://www.gruenekoeln.de/veedel/innenstadtdeutz/",
      address: "Ebertplatz 23, 50668 Köln, Germany",
      faqs: [
        {
          question: "Wie kann ich aktiv mitmachen?",
          answer:
            "Wenn Du dich für die Politik vor Deiner Kölner Haustür interessierst, bist Du hier genau richtig. Erfahre auf unserer Website wie die GRÜNEN in der Innenstadt und in Deutz ihre Politik umsetzen. Wenn Du Lust hast, dabei mitzumachen, bist Du jederzeit willkommen, egal ob Grünes Mitglied oder Interessierte*r. Nimm einfach zu uns Kontakt auf. ",
        },
        {
          question: "Gibt es regelmäßige Veranstaltungen?",
          answer:
            "Bei unseren regelmäßig stattfindenden Stammtischen stehen die Themen und Fragen der Kölnerinnen und Kölner im Vordergrund. Grüne PolitikerInnen aus Bund, Land und vor allem aus Kölle stehen Rede und Antwort. Momentan finden die Stammtische digital statt.",
        },
      ],
      title: "Die Grünen – Innenstadt/Deutz",
    },
    {
      weblink: "https://www.ernaehrungsrat-koeln.de/",
      longitude: 6.9506576,
      organizationType: "Vereine",
      createdAt: "2022-02-14T14:04:44.886Z",
      latitude: 50.9402895,
      faqs: [
        {
          question: "Was wollen wir?",
          answer:
            "Wir möchten die Ernährungspolitik zurück in die Region holen, auf die kommunale Ebene. Wir forcieren einen aktiven Dialog zwischen Politik, Verwaltung, Erzeuger:innen, Vertrieben und Verbraucher:innen, um so langfristig und nachhaltig die Strukturen einer regionalen Lebensmittelversorgung zu stärken. Gleichzeitig möchten wir Informations- und Aktionsplattform für engagierte Bürger:innen sein, die sich für ein regionales Ernährungssystem einsetzen möchten. Wir fördern den Austausch unter Akteur:innen, Ehrenamtlichen und Bildungsträgern.",
        },
        {
          answer:
            "Der Ernährungsrat für Köln und Umgebung e.V. arbeitet, unter Beteiligung einer breiten Öffentlichkeit, an einem Politikziel für die Kommune Köln. Faire Partnerschaften zwischen Kommunen und Landwirt:innen, einfache Zugänge für Städter:innen zu lokalen Produkten aus bäuerlicher Landwirtschaft oder aber die Vereinfachung des Marktzugangs für familiäre Landwirtschaftsbetriebe sind Alternativen zur immer weiter fortschreitenden Zentralisierung am Lebensmittelmarkt. Es ist die Grundlage für einen mentalen Wandel, der notwendig ist, um regionale Kreisläufe zu stärken und weiteren Kontrollverlust bei der Herkunft unserer Lebensmittel zu verhindern.                                                                                                                                              Daneben führen wir Bildungskampagnen mit dem Ziel durch, ein Bewusstsein für den Wert der Lebensmittel und der nachhaltigen Landwirtschaft zu erzeugen und somit einen bewussteren Konsum zu fördern und die Nachfrage nach entspr. Produkten zu fördern.",
          question: "Was machen wir?",
        },
      ],
      userIds: ["qkbwKh9DT3h4h6yPsH8D7GqYRXC3", "6SLhQDZuurdUkDALsc9P7T3GMv82"],
      title: "Ernährungsrat Köln",
      contactTitle: "E-Mail",
      address: "Neven-Dumont-Straße 14, 50667 Köln, Germany",
      organizationId: "xGkDswuiy3Uk4nk3LIN6",
      contact: "info@ernaehrungsrat.koeln",
      status: "active",
      description:
        "Der Ernährungsrat für Köln und Umgebung wurde im März 2016 als erster Ernährungsrat in Deutschland gegründet. Unser Ziel ist eine Stadt in der Lebensmittel mit und für Menschen und Tiere angebaut werden und wachsen können. Ob auf öffentlichen Flächen, Brachen, Seitenstreifen, in Hochbeeten, auf Parkplätzen, Gemeinschaft,- Lehr-, oder Kleingärten - lass uns das Essbare in die Stadt zurück bringen!",
      logoURL:
        "https://firebasestorage.googleapis.com/v0/b/senf-prod.appspot.com/o/organizationsData%2FxGkDswuiy3Uk4nk3LIN6%2Flogo%2Flogo?alt=media&token=b7668637-725d-4249-a84a-8a18237a2ecc",
      weblinkTitle: "Website",
    },
  ],
};

export const SearchOpen = Template.bind({});
SearchOpen.args = {
  searchOpen: true,
  order: "ideas",
  selectedTopics: ["Versorgung"],

  ideasData: [
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
    {
      screamId: "omweqsDYlFMkmTFAX1Ba",
      lat: 50.96734458192481,
      long: 7.00181320821256,
      title: "Straßenfest an der Wallstraße",
      body: "Vom Abschnitt Ecke Wallstr. bis Springbrunnen wird geplant ein Straßenfest zu veranstalten. Wohnst du in der Straße und willst deine Nachbar:innen ken",
      createdAt: "2021-07-12T11:10:22.413Z",
      commentCount: 0,
      likeCount: 1,
      status: "None",
      Thema: "Sport / Freizeit",
      Stadtteil: "Mülheim",
      color: "#f6c095",
      locationHeader: "Mülheimer Freiheit 142",
    },
  ],
};
